#ifndef GUARD_CONSTANTS_ABILITIES_H
#define GUARD_CONSTANTS_ABILITIES_H

#define ABILITY_NONE 0
#define ABILITY_STENCH 1
#define ABILITY_DRIZZLE 2
#define ABILITY_SPEED_BOOST 3
#define ABILITY_BATTLE_ARMOR 4
#define ABILITY_STURDY 5
#define ABILITY_DAMP 6
#define ABILITY_LIMBER 7
#define ABILITY_SAND_VEIL 8
#define ABILITY_STATIC 9
#define ABILITY_VOLT_ABSORB 10
#define ABILITY_WATER_ABSORB 11
#define ABILITY_OBLIVIOUS 12
#define ABILITY_CLOUD_NINE 13
#define ABILITY_COMPOUND_EYES 14
#define ABILITY_INSOMNIA 15
#define ABILITY_COLOR_CHANGE 16
#define ABILITY_IMMUNITY 17
#define ABILITY_FLASH_FIRE 18
#define ABILITY_SHIELD_DUST 19
#define ABILITY_OWN_TEMPO 20
#define ABILITY_SUCTION_CUPS 21
#define ABILITY_INTIMIDATE 22
#define ABILITY_SHADOW_TAG 23
#define ABILITY_ROUGH_SKIN 24
#define ABILITY_WONDER_GUARD 25
#define ABILITY_LEVITATE 26
#define ABILITY_EFFECT_SPORE 27
#define ABILITY_SYNCHRONIZE 28
#define ABILITY_CLEAR_BODY 29
#define ABILITY_NATURAL_CURE 30
#define ABILITY_LIGHTNING_ROD 31
#define ABILITY_SERENE_GRACE 32
#define ABILITY_SWIFT_SWIM 33
#define ABILITY_CHLOROPHYLL 34
#define ABILITY_ILLUMINATE 35
#define ABILITY_TRACE 36
#define ABILITY_HUGE_POWER 37
#define ABILITY_POISON_POINT 38
#define ABILITY_INNER_FOCUS 39
#define ABILITY_MAGMA_ARMOR 40
#define ABILITY_WATER_VEIL 41
#define ABILITY_MAGNET_PULL 42
#define ABILITY_SOUNDPROOF 43
#define ABILITY_RAIN_DISH 44
#define ABILITY_SAND_STREAM 45
#define ABILITY_PRESSURE 46
#define ABILITY_THICK_FAT 47
#define ABILITY_EARLY_BIRD 48
#define ABILITY_FLAME_BODY 49
#define ABILITY_RUN_AWAY 50
#define ABILITY_KEEN_EYE 51
#define ABILITY_HYPER_CUTTER 52
#define ABILITY_PICKUP 53
#define ABILITY_TRUANT 54
#define ABILITY_HUSTLE 55
#define ABILITY_CUTE_CHARM 56
#define ABILITY_PLUS 57
#define ABILITY_MINUS 58
#define ABILITY_FORECAST 59
#define ABILITY_STICKY_HOLD 60
#define ABILITY_SHED_SKIN 61
#define ABILITY_GUTS 62
#define ABILITY_MARVEL_SCALE 63
#define ABILITY_LIQUID_OOZE 64
#define ABILITY_OVERGROW 65
#define ABILITY_BLAZE 66
#define ABILITY_TORRENT 67
#define ABILITY_SWARM 68
#define ABILITY_ROCK_HEAD 69
#define ABILITY_DROUGHT 70
#define ABILITY_ARENA_TRAP 71
#define ABILITY_VITAL_SPIRIT 72
#define ABILITY_WHITE_SMOKE 73
#define ABILITY_PURE_POWER 74
#define ABILITY_SHELL_ARMOR 75
#define ABILITY_CACOPHONY 76
#define ABILITY_AIR_LOCK 77
#define ABILITY_TRANSISTOR 78
#define ABILITY_DRAGONS_MAW 79
#define ABILITY_MULTITYPE 80
#define ABILITY_PIXILATE 81
// Abilities added for Mega Evolution and Gen 6+ forms
#define ABILITY_TOUGH_CLAWS      82  // Mega Charizard X, Mega Aerodactyl, Mega Metagross
#define ABILITY_AERILATE         83  // Mega Pinsir, Mega Salamence
#define ABILITY_MOLD_BREAKER     84  // Mega Gyarados, Mega Ampharos
#define ABILITY_MEGA_LAUNCHER    85  // Mega Blastoise
#define ABILITY_PARENTAL_BOND    86  // Mega Kangaskhan
#define ABILITY_MAGIC_BOUNCE     87  // Mega Absol
#define ABILITY_STRONG_JAW       88  // Mega Sharpedo
#define ABILITY_SHEER_FORCE      89  // Mega Camerupt
#define ABILITY_SKILL_LINK       90  // Mega Heracross
#define ABILITY_SOLAR_POWER      91  // Mega Houndoom
#define ABILITY_REFRIGERATE      92  // Mega Glalie
#define ABILITY_FILTER           93  // Mega Aggron
#define ABILITY_TECHNICIAN       94  // Mega Scizor
#define ABILITY_STEADFAST        95  // Mega Mewtwo X
// Mega Mewtwo Y uses existing ABILITY_INSOMNIA (15)
#define ABILITY_PRANKSTER        96  // Mega Banette
#define ABILITY_DELTA_STREAM     97  // Mega Rayquaza — weather: Mysterious Air Current
#define ABILITY_PRIMORDIAL_SEA   98  // Primal Kyogre — weather: Heavy Rain
#define ABILITY_DESOLATE_LAND    99  // Primal Groudon — weather: Extremely Harsh Sunlight
#define ABILITY_ADAPTABILITY    100  // Mega Beedrill, Mega Lucario
#define ABILITY_NORMALIZE       101  // Mega Glalie alt
#define ABILITY_NO_GUARD        102  // Mega Pidgeot
#define ABILITY_SAND_FORCE      103  // Mega Steelix, Mega Garchomp
#define ABILITY_SCRAPPY         104  // Mega Lopunny
#define ABILITY_SNOW_WARNING    105  // Mega Abomasnow
#define ABILITY_HEALER          106  // Mega Audino

#define ABILITIES_COUNT 107

#endif  // GUARD_CONSTANTS_ABILITIES_H
