name: Build ROM with Docker
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm # משתמש בסביבה מוכנה מראש ל-GBA
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y build-essential python3 libpng-dev wget git

      - name: Setup agbcc
        run: |
          git clone https://github.com
          cd agbcc
          sh build.sh
          sh install.sh ../
          cd ..

      - name: Get Base ROM
        run: |
          wget -O baserom.gba "https://archive.org"

      - name: Build ROM
        run: |
          make -j$(nproc)

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: PokemonHnS-Final-ROM
          path: "*.gba"
